# Generated by Django 4.1.4 on 2023-01-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("user_name", models.CharField(max_length=30)),
                ("phone", models.CharField(blank=True, max_length=16, null=True)),
                ("city", models.CharField(blank=True, max_length=16, null=True)),
                ("province", models.CharField(blank=True, max_length=16, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("country", models.CharField(blank=True, max_length=10, null=True)),
                ("package", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "no_of_acres",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("package_renew", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
