# Generated by Django 4.1.4 on 2023-05-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="test_name",
            field=models.CharField(max_length=50),
        ),
    ]
